### ISSUE TITLE
[bug] wrong assignment of aliases

### ISSUE THREAD

**Issue by blckbx** [smallworlnd/LNnodeInsight#8]
Aliases seemd to be wrongly assigned to its corresponding channel representation when choosing four peers. 

Example:
![lnnodeinsight_bug](https://user-images.githubusercontent.com/74455114/203070493-d720441f-a461-47d9-b5c0-4ecac4373e0c.png)

This is reproducable for any four chosen peers.

**Comment by smallworlnd** [comment]
Pushed a fix, looks good on my side now, according to this screenshot.

![vennfix](https://user-images.githubusercontent.com/85709046/203210215-a82e41b7-3325-4e8b-844f-0833a1a93a9a.png)

**Comment by blckbx** [comment]
Works perfectly fine. Thanks!
